//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCAB_Debugger_ACS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winMainTop {
            get {
                return ((double)(this["winMainTop"]));
            }
            set {
                this["winMainTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winMainLeft {
            get {
                return ((double)(this["winMainLeft"]));
            }
            set {
                this["winMainLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winMainHeight {
            get {
                return ((double)(this["winMainHeight"]));
            }
            set {
                this["winMainHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winMainWidth {
            get {
                return ((double)(this["winMainWidth"]));
            }
            set {
                this["winMainWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool winMainMaximized {
            get {
                return ((bool)(this["winMainMaximized"]));
            }
            set {
                this["winMainMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winPosMonitorTop {
            get {
                return ((double)(this["winPosMonitorTop"]));
            }
            set {
                this["winPosMonitorTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winPosMonitorLeft {
            get {
                return ((double)(this["winPosMonitorLeft"]));
            }
            set {
                this["winPosMonitorLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winPosMonitorHeight {
            get {
                return ((double)(this["winPosMonitorHeight"]));
            }
            set {
                this["winPosMonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winPosMonitorWidth {
            get {
                return ((double)(this["winPosMonitorWidth"]));
            }
            set {
                this["winPosMonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool winPosMonitorMaximized {
            get {
                return ((bool)(this["winPosMonitorMaximized"]));
            }
            set {
                this["winPosMonitorMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winSnsMonitorTop {
            get {
                return ((double)(this["winSnsMonitorTop"]));
            }
            set {
                this["winSnsMonitorTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winSnsMonitorLeft {
            get {
                return ((double)(this["winSnsMonitorLeft"]));
            }
            set {
                this["winSnsMonitorLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winSnsMonitorHeight {
            get {
                return ((double)(this["winSnsMonitorHeight"]));
            }
            set {
                this["winSnsMonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winSnsMonitorWidth {
            get {
                return ((double)(this["winSnsMonitorWidth"]));
            }
            set {
                this["winSnsMonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool winSnsMonitorMaximized {
            get {
                return ((bool)(this["winSnsMonitorMaximized"]));
            }
            set {
                this["winSnsMonitorMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USB シリアル デバイス (COM20)")]
        public string spCaption0 {
            get {
                return ((string)(this["spCaption0"]));
            }
            set {
                this["spCaption0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USB シリアル デバイス (COM21)")]
        public string spCaption1 {
            get {
                return ((string)(this["spCaption1"]));
            }
            set {
                this["spCaption1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USB シリアル デバイス (COM22)")]
        public string spCaption2 {
            get {
                return ((string)(this["spCaption2"]));
            }
            set {
                this["spCaption2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USB シリアル デバイス (COM23)")]
        public string spCaption3 {
            get {
                return ((string)(this["spCaption3"]));
            }
            set {
                this["spCaption3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int spBaudRate0 {
            get {
                return ((int)(this["spBaudRate0"]));
            }
            set {
                this["spBaudRate0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int spBaudRate1 {
            get {
                return ((int)(this["spBaudRate1"]));
            }
            set {
                this["spBaudRate1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int spBaudRate2 {
            get {
                return ((int)(this["spBaudRate2"]));
            }
            set {
                this["spBaudRate2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int spBaudRate3 {
            get {
                return ((int)(this["spBaudRate3"]));
            }
            set {
                this["spBaudRate3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000011")]
        public string sn11 {
            get {
                return ((string)(this["sn11"]));
            }
            set {
                this["sn11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000012")]
        public string sn12 {
            get {
                return ((string)(this["sn12"]));
            }
            set {
                this["sn12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000013")]
        public string sn13 {
            get {
                return ((string)(this["sn13"]));
            }
            set {
                this["sn13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000021")]
        public string sn21 {
            get {
                return ((string)(this["sn21"]));
            }
            set {
                this["sn21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000022")]
        public string sn22 {
            get {
                return ((string)(this["sn22"]));
            }
            set {
                this["sn22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000023")]
        public string sn23 {
            get {
                return ((string)(this["sn23"]));
            }
            set {
                this["sn23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000031")]
        public string sn31 {
            get {
                return ((string)(this["sn31"]));
            }
            set {
                this["sn31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000032")]
        public string sn32 {
            get {
                return ((string)(this["sn32"]));
            }
            set {
                this["sn32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000033")]
        public string sn33 {
            get {
                return ((string)(this["sn33"]));
            }
            set {
                this["sn33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int view {
            get {
                return ((int)(this["view"]));
            }
            set {
                this["view"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winPhaseMonitorTop {
            get {
                return ((double)(this["winPhaseMonitorTop"]));
            }
            set {
                this["winPhaseMonitorTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winPhaseMonitorLeft {
            get {
                return ((double)(this["winPhaseMonitorLeft"]));
            }
            set {
                this["winPhaseMonitorLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winPhaseMonitorHeight {
            get {
                return ((double)(this["winPhaseMonitorHeight"]));
            }
            set {
                this["winPhaseMonitorHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double winPhaseMonitorWidth {
            get {
                return ((double)(this["winPhaseMonitorWidth"]));
            }
            set {
                this["winPhaseMonitorWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool winPhaseMonitorMaximized {
            get {
                return ((bool)(this["winPhaseMonitorMaximized"]));
            }
            set {
                this["winPhaseMonitorMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string logSaveDirPath {
            get {
                return ((string)(this["logSaveDirPath"]));
            }
            set {
                this["logSaveDirPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saveLogs {
            get {
                return ((bool)(this["saveLogs"]));
            }
            set {
                this["saveLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public uint snsIntTime {
            get {
                return ((uint)(this["snsIntTime"]));
            }
            set {
                this["snsIntTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5800")]
        public uint FreqMHz {
            get {
                return ((uint)(this["FreqMHz"]));
            }
            set {
                this["FreqMHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool saveLogsPOS {
            get {
                return ((bool)(this["saveLogsPOS"]));
            }
            set {
                this["saveLogsPOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool saveLogsPTU1x {
            get {
                return ((bool)(this["saveLogsPTU1x"]));
            }
            set {
                this["saveLogsPTU1x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool saveLogsPTU2x {
            get {
                return ((bool)(this["saveLogsPTU2x"]));
            }
            set {
                this["saveLogsPTU2x"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool saveLogsPTU3x {
            get {
                return ((bool)(this["saveLogsPTU3x"]));
            }
            set {
                this["saveLogsPTU3x"] = value;
            }
        }
    }
}
